[package]
name = "nex-ballast"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = { version = "2.3.1", default-features=false }
async-net = { version = "2.0.0", default-features=false }
eframe = { version = "0.29.1", default-features = false, features = ["default_fonts", "glow"] }
egui-toast = "0.15.0"
egui_extras = { version = "0.29.1", default-features = false, features = ["image"] }
env_logger = { version = "0.11.5", default-features = false }
eyre = "0.6.12"
futures-lite = { version = "2.3.0", default-features=false }
# https://github.com/emilk/egui/issues/4464#issuecomment-2096170087
image = { version = "0.25", default-features = false, features = ["jpeg"] }
log = { version = "0.4.22", default-features = false }
oneshot = { version = "0.1.8", default-features=false }
url = { version = "2.5.2", default-features = false }
